import './globals.css'
import { Inter } from 'next/font/google'
import { ChakraProvider } from '@chakra-ui/react'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Modal Generic',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="pt-BR">
      <body className={`${inter.className} flex items-center justify-center w-screen h-screen bg-red-600`}>
      <ChakraProvider>
          {children}  
      </ChakraProvider>
      </body>
    </html>
  )
}
